### ISSUE TITLE
Change factorial function in `combination`

### ISSUE THREAD

**Issue by bblodfon** [dpaukov/combinatoricslib#23]
Hi @dpaukov ,

I've been using this version of the library and an issue arose, which I believe is minimal work to correct, so here it is:

I use the [getNumberOfGeneratedObjects](https://github.com/dpaukov/combinatoricslib/blob/eb297fa87cec3fd9d9a4947270a74ee4135194c4/src/main/java/org/paukov/combinatorics/combination/simple/SimpleCombinationGenerator.java#L94) function which uses the simple [factorial](https://github.com/dpaukov/combinatoricslib/blob/eb297fa87cec3fd9d9a4947270a74ee4135194c4/src/main/java/org/paukov/combinatorics/util/Util.java#L39) and not the one with the `BigDecimal` type, so when in my application I happened to use in the [combination(n,k)](https://github.com/dpaukov/combinatoricslib/blob/eb297fa87cec3fd9d9a4947270a74ee4135194c4/src/main/java/org/paukov/combinatorics/util/Util.java#L77), n=21 and k=0 respectively, it return zero for the denominator. (factorial(21) > max Long). 

If instead the `Util.combination(n,k)` function was using the BigDecimal factorial, and only after the calculation it converted to long type, that would an easy and satisfiable fix for me (^-^)

**Comment by dpaukov** [comment]
The change has been released in version 2.3 today.
